window.AZ104_CURRICULUM={
identity:{path:'https://learn.microsoft.com/en-us/training/paths/az-104-manage-identities-governance/',sections:[
{title:'Microsoft Entra users and groups',intro:'L’identité dit qui se connecte ; les rôles et licences déterminent ensuite ce qu’elle peut utiliser.',items:[
['Users and groups','Savoir distinguer membre, invité, groupe de sécurité et groupe Microsoft 365. Les propriétés d’un utilisateur et l’appartenance aux groupes peuvent influencer l’accès.','Microsoft Entra ID → Users/Groups : crée un groupe test, ajoute un membre et observe ses propriétés.','Ne suppose pas qu’un groupe Entra donne automatiquement un rôle Azure.'],
['Licenses','Repérer qu’une fonctionnalité Entra peut dépendre d’une licence et que l’attribution peut se faire à l’utilisateur ou par groupe.','Microsoft Entra ID → Licenses : regarde les licences disponibles, les affectations et les erreurs. Ne crée pas d’abonnement payant pour le lab.','Une licence donne une fonctionnalité, pas un rôle RBAC sur les ressources.'],
['External users (B2B)','Un invité externe reçoit une identité dans le tenant ; invitation, accès à une application et accès RBAC sont des étapes distinctes.','Microsoft Entra ID → Users → Invite external user ; examine le type Guest et les groupes/rôles nécessaires.','Invitation acceptée ne signifie pas accès à tous les resource groups.'],
['Self-service password reset (SSPR)','Identifier qui est inclus dans SSPR, les méthodes d’authentification demandées et les effets de la configuration.','Microsoft Entra ID → Password reset : examine Properties, Authentication methods et Registration. Vérifie d’abord les prérequis de licence.','SSPR n’est pas la même opération qu’un administrateur réinitialisant un mot de passe.']]},
{title:'Azure RBAC',intro:'Une attribution = principal + role definition + scope. L’accès s’hérite vers les enfants de l’étendue.',items:[
['Built-in roles','Reader lit le plan de gestion ; Contributor gère les ressources ; Owner gère aussi les attributions ; User Access Administrator gère l’accès. Compare les actions exactes du rôle si le scénario est précis.','Sur un resource group → Access control (IAM) → Roles : inspecte les permissions d’un rôle avant de l’attribuer.','Azure roles et Microsoft Entra roles n’administrent pas la même chose.'],
['Scope and assignments','Management group → subscription → resource group → resource. Une attribution à un parent s’applique aux enfants ; privilégie le plus petit scope utile.','IAM → Check access ou Role assignments : sélectionne un utilisateur et note les rôles directs et hérités.','L’absence de rôle direct sur la ressource ne signifie pas absence d’accès hérité.'],
['Data plane vs management plane','Un rôle qui permet de gérer un Storage account ne donne pas nécessairement accès aux données Blob. Cherche le rôle de données demandé.','Compare Reader et Storage Blob Data Reader dans IAM, puis teste avec un utilisateur disposant des permissions appropriées.','Reader ≠ Storage Blob Data Reader.']]},
{title:'Subscriptions and governance',intro:'Policy fixe des règles ; un lock protège ; tags classent ; Cost Management aide à maîtriser les dépenses.',items:[
['Management groups and subscriptions','Les management groups permettent d’appliquer une gouvernance à plusieurs subscriptions. Une subscription sert notamment de limite de facturation et d’accès.','Portal → Management groups : observe la hiérarchie ; Subscription → Access control et Cost Management.','Une subscription peut appartenir à un management group ; le groupe de ressources se trouve dans une seule subscription.'],
['Resource groups and tags','Un resource group regroupe le cycle de vie des ressources ; les tags aident à les classer et à analyser le coût. Les tags ne sont pas tous hérités automatiquement.','Crée un resource group test et un tag purpose=az104 ; cherche ensuite par tag dans le Portal ou Azure CLI.','Supprimer un resource group supprime aussi ses ressources.'],
['Azure Policy','Une policy definition et une assignment évaluent les ressources. Savoir reconnaître deny, audit et modify ainsi que le niveau d’assignation.','Portal → Policy → Definitions puis Assignments : lis une définition built-in et prévisualise le scope avant de l’assigner.','RBAC autorise un acteur ; Policy contrôle les ressources créées ou configurées.'],
['Resource locks','CanNotDelete bloque la suppression ; ReadOnly bloque les écritures du plan de gestion et peut gêner des opérations indirectes.','Lab 1 : crée un lock sur un groupe test, inspecte son héritage, puis supprime le lock avant le groupe.','Owner n’ignore pas simplement un lock : il faut le retirer avec les permissions nécessaires.'],
['Budgets, alerts and Advisor','Un budget suit ou alerte sur un seuil ; il n’arrête pas automatiquement les ressources. Advisor propose des recommandations ; les alertes de coûts aident à surveiller.','Cost Management → Budgets : configure un budget de test et examine les destinataires ; Advisor : lis une recommandation sans l’appliquer aveuglément.','Un budget n’est pas une limite dure de dépense.']]}],sources:[['Entra documentation','https://learn.microsoft.com/en-us/entra/identity/'],['RBAC scope','https://learn.microsoft.com/en-us/azure/role-based-access-control/scope-overview'],['Azure Policy','https://learn.microsoft.com/en-us/azure/governance/policy/overview']]},
storage:{path:'https://learn.microsoft.com/en-us/training/paths/az-104-manage-storage/',sections:[
{title:'Storage access',intro:'Pour lire une donnée il faut à la fois un trajet réseau possible et une autorisation valable.',items:[
['Storage firewall and virtual networks','Public network access et firewall filtrent le point d’entrée public. Un service endpoint identifie le subnet ; un private endpoint apporte une IP privée et demande une résolution DNS correcte.','Storage account → Networking : observe le mode choisi ; compare la résolution DNS avant/après un private endpoint dans un environnement de test.','L’ouverture du firewall n’attribue aucun rôle de données.'],
['SAS tokens','Service SAS, account SAS et user delegation SAS n’ont pas le même signataire ni la même portée. Limite durée, ressource et permissions.','Sur un conteneur test, génère une SAS Read courte et vérifie sa date d’expiration ; évite de publier l’URL signée.','Une SAS est un secret donnant les droits qu’elle contient.'],
['Stored access policies','Une stored access policy contrôle et peut révoquer les service SAS qui y font référence ; elle ne s’applique pas aux user delegation SAS.','Storage container → Access policy : crée une policy, lie une service SAS, puis retire la policy pour comprendre la révocation.','Ne généralise pas cette méthode de révocation à toutes les familles de SAS.'],
['Account keys and Azure Files identity','Les clés du compte donnent un accès étendu ; Azure Files peut utiliser une authentification fondée sur l’identité selon sa configuration. Distigue partage SMB, rôle de partage et permissions de fichiers.','Storage account → Access keys : repère la rotation ; File shares → Identity-based access : étudie les prérequis avant de configurer.','Le rôle de gestion du compte ne suffit pas toujours pour monter un partage Azure Files.']]},
{title:'Storage accounts',intro:'Choisis l’account kind, la redondance, les protections et les outils de transfert selon le besoin.',items:[
['Account kind and configuration','StorageV2 est le choix généraliste courant. Regarde région, performance, SKU, accès public et minimum TLS.','Lab 2 : crée un StorageV2 Standard_LRS et relis sa configuration avec az storage account show.','Storage account est le conteneur de plusieurs services, pas seulement Blob.'],
['Redundancy','LRS reste local ; ZRS traverse les zones ; GRS ajoute une région secondaire ; GZRS combine zones et région. RA permet la lecture secondaire selon l’offre.','Dessine la panne à couvrir : disque/datacenter, zone ou région ; associe une redondance compatible et vérifie la disponibilité régionale.','La réplication ne remplace pas un historique de sauvegarde.'],
['Object replication','Object replication copie des block blobs entre comptes selon des règles ; elle a des conditions de versioning et une portée différente de la redondance du compte.','Portal → Storage account → Object replication : lis les prérequis et la règle source/destination avant toute création.','GRS et object replication ne se configurent pas pour exactement le même objectif.'],
['Encryption','Le chiffrement du stockage est activé côté service. Distingue Microsoft-managed keys, customer-managed keys, encryption scopes et chiffrement en transit par HTTPS/TLS.','Storage account → Encryption et Configuration : identifie la source des clés et le minimum TLS.','Clé client dans Key Vault implique identité et permissions : ne te contente pas du nom de la clé.'],
['Storage Explorer and AzCopy','Storage Explorer est un outil graphique ; AzCopy transfère des volumes de données. Savoir choisir authentification et source/destination.','Ouvre Storage Explorer sur un compte test ; lis azcopy login et azcopy copy dans la documentation avant un transfert.','Ne colle pas un SAS dans un dépôt public.']]},
{title:'Azure Files and Blob Storage',intro:'Azure Files sert les partages ; Blob stocke des objets. Les mécanismes de récupération ne sont pas interchangeables.',items:[
['Azure Files shares and snapshots','Créer un file share, choisir quota/tiers selon l’offre, monter le partage et prendre un snapshot. Soft delete protège contre la suppression du partage selon la rétention.','Portal → File shares : crée un partage test, inspecte snapshots et soft delete.','Un snapshot Azure Files ne vaut pas un snapshot Blob.'],
['Blob containers and access tiers','Un container regroupe des blobs. Hot, cool, cold et archive échangent coût de stockage contre coût et délai d’accès ; archive exige une réhydratation.','Portal → Containers : crée un conteneur privé et compare les access tiers d’un block blob.','Lifecycle ne réhydrate pas automatiquement un blob archivé vers un niveau en ligne.'],
['Blob soft delete and versioning','Soft delete garde temporairement un blob supprimé ; versioning permet de retrouver des versions antérieures après modification. Les réglages et rétentions sont distincts.','Lab 2 : active Blob soft delete, puis inspecte Data protection et Blob versioning séparément.','Une suppression permanente après la rétention n’est pas récupérée par soft delete.'],
['Lifecycle management','Les règles ciblent certains blobs et appliquent transition de tier ou suppression selon des conditions ; vérifie les versions et snapshots concernés.','Portal → Lifecycle management : compose une règle test sans la sauvegarder, puis explique son filtre et son effet.','Une règle de lifecycle peut déplacer un blob réhydraté si les conditions restent vraies.']]}],sources:[['Storage documentation','https://learn.microsoft.com/en-us/azure/storage/'],['Redundancy','https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy'],['Data protection','https://learn.microsoft.com/en-us/azure/storage/blobs/data-protection-overview']]},
compute:{path:'https://learn.microsoft.com/en-us/training/paths/az-104-manage-compute-resources/',sections:[
{title:'ARM templates and Bicep',intro:'Décrire le résultat souhaité, inspecter les dépendances puis vérifier le changement avant et après déploiement.',items:[
['Interpret and modify templates','Repère paramètres, variables, ressources, API versions, dépendances et outputs. Bicep exprime les références symboliques plus lisiblement que JSON ARM.','Lis labs/03-bicep/main.bicep : change le SKU dans une branche de test et explique l’effet sans déployer.','Un template valide syntaxiquement peut échouer faute de quota, de permission ou de SKU régional.'],
['Deploy and what-if','Déploiement à l’étendue du resource group, subscription ou management group selon le type de ressource. what-if montre les changements attendus.','Lab 3 : az deployment group what-if, puis az deployment group create ; compare l’output et l’état réel.','what-if est une prévision, pas une garantie absolue du déploiement.'],
['Export and convert','Exporter un déploiement ou un template ARM aide à comprendre l’existant ; le code exporté mérite souvent d’être simplifié. Bicep CLI peut décompiler de l’ARM JSON.','Portal → Deployments → Export template sur une ressource test ; compare le JSON au Bicep écrit à la main.','Un export n’est pas automatiquement un module propre, portable et sûr.']]},
{title:'Virtual machines',intro:'Pour chaque VM, sépare taille, disque, réseau, disponibilité et gestion du cycle de vie.',items:[
['Create, resize and move','La taille impose CPU/RAM et dépend du quota et de la région ; déplacer une VM entre groupes/abonnements ou régions a des contraintes différentes.','Portal → Create VM sans valider : note image, taille, zone, disque, NIC ; vérifie les tailles disponibles sur ton abonnement.','Un déplacement de région n’est pas la même opération qu’un move de resource group.'],
['Managed disks and encryption at host','Disques OS et data ont types/performance ; snapshots et chiffrement répondent à d’autres besoins. Encryption at host chiffre les données au niveau de l’hôte pour les VM compatibles.','Sur la page VM → Disks/Encryption : compare types de disque et prérequis de encryption at host.','Un snapshot manuel n’est pas à lui seul une politique de sauvegarde.'],
['Availability zones and sets','Zones répartissent physiquement dans une région ; availability sets utilisent fault/update domains ; VMSS gère un parc réplicable et son scaling.','Dessine deux VM sur deux zones, puis deux VM dans un set ; énonce quelle panne chaque conception vise.','Un seul exemplaire dans un VMSS ne fournit pas de haute disponibilité applicative.'],
['Virtual Machine Scale Sets','VMSS décrit un modèle de VM, une capacité et des règles de scale-out/in. Observe modes, orchestration et health selon le scénario.','Portal → VM scale sets → Create : lis les choix de capacity et scaling sans créer de pool si ton quota étudiant est limité.','Scale-out n’est utile que si l’application et sa donnée supportent plusieurs instances.']]},
{title:'Containers',intro:'Registry stocke les images ; ACI et Container Apps les exécutent avec des niveaux différents de gestion.',items:[
['Azure Container Registry (ACR)','ACR stocke les images ; pense tag, authentification, permissions pull/push et région.','Lis un dépôt ACR existant si tu en as un ; identifie image et tag, puis explique comment une identité obtient AcrPull.','ACR seul ne sert aucune requête HTTP à l’application.'],
['Azure Container Instances (ACI)','ACI lance un ou plusieurs conteneurs sans cluster à administrer ; configure image, ressources, ports et variables.','Portal → Container instances → Create sans valider : repère image, CPU/mémoire, réseau et redémarrage.','Pas de cluster Kubernetes ni de mise à l’échelle automatique comme un orchestrateur complet.'],
['Azure Container Apps','Container Apps apporte ingress, révisions, environnement et scaling ; distingue ces objets de l’image ACR.','Dans un environnement de test existant, observe revisions, replicas et règles de scaling.','Une application à zéro replica peut demander un démarrage à froid selon la configuration.']]},
{title:'Azure App Service',intro:'Le plan est la capacité facturée ; la Web App est l’application ; les slots servent à publier une nouvelle version.',items:[
['Plan, app and scaling','Le plan fixe région, OS, SKU et capacité. Scale up change le SKU ; scale out change le nombre d’instances.','Sur une Web App existante, compare Scale up et Scale out sans appliquer un palier payant.','Les deployment slots et certaines options dépendent du niveau de plan.'],
['Certificates, TLS and custom domain','Le hostname personnalisé nécessite une validation DNS. HTTPS requiert un certificat adapté ; règle le minimum TLS selon les exigences.','Portal → Custom domains et TLS/SSL : lis les étapes TXT/CNAME/A et les certificats disponibles.','Créer une entrée DNS ne génère pas à lui seul un certificat valide.'],
['Backup, networking and deployment slots','Backup dépend du plan et des paramètres ; VNet Integration vise la sortie vers le VNet ; Private Endpoint sert l’entrée privée ; slot staging précède le swap.','Sur une Web App de test : repère Backup, Networking et Deployment slots, puis explique le flux staging → test → swap.','VNet Integration seule ne rend pas la Web App privée en entrée.']]}],sources:[['Compute learning path','https://learn.microsoft.com/en-us/training/paths/az-104-manage-compute-resources/'],['Bicep overview','https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview'],['App Service docs','https://learn.microsoft.com/en-us/azure/app-service/overview']]},
network:{path:'https://learn.microsoft.com/en-us/training/paths/az-104-manage-virtual-networks/',sections:[
{title:'Virtual networks and routing',intro:'Résolution DNS → route effective → filtrage → destination : utilise cet ordre pour déboguer.',items:[
['VNets and subnets','Les CIDR des subnets sont inclus dans ceux du VNet et ne se chevauchent pas. Une NIC reçoit une adresse privée dans un subnet.','Lab 4 : crée un VNet /16 et un subnet /24 ; inspecte le préfixe réel.','Une adresse publique sur une ressource ne remplace pas son adresse privée.'],
['VNet peering','Peering connecte directement deux VNets ; vérifie plages non chevauchantes, direction des connexions et options de transit/gateway.','Dessine A↔B et B↔C ; puis vérifie quelles connexions supplémentaires rendent le trajet A↔C possible.','Le peering n’est pas transitif par défaut.'],
['Public IP addresses','Une IP publique peut être liée à certains frontends ou interfaces ; SKU, allocation et zone influencent son comportement.','Portal → Public IP addresses → Create sans valider : compare SKU, assignment et zone avant le prix.','Une VM avec IP publique exige quand même des règles réseau pour autoriser le trafic.'],
['User-defined routes (UDR)','Une route a un préfixe et un prochain saut. Compare route système, BGP et UDR puis examine les effective routes.','Dessine une route 0.0.0.0/0 vers une virtual appliance ; explique le retour du trafic avant tout déploiement.','NSG filtre, UDR route : ne confonds pas les deux.'],
['Connectivity troubleshooting','Commence par DNS, IP, route, NSG, firewall et écoute du service ; Connection troubleshoot et les effective routes/rules montrent où le trajet échoue.','Sur une VM existante seulement, utilise Network Watcher → Connection troubleshoot ; note source, destination et port.','Ping seul n’explique pas une application TCP qui ne répond pas.']]},
{title:'Secure access',intro:'NSG filtre le trafic ; endpoints contrôlent le chemin vers les services Azure ; Bastion sert à administrer.',items:[
['NSG and ASG','Un NSG contient règles inbound/outbound ordonnées par priorité ; les ASG groupent des NIC pour les cibler dans les règles.','Lab 4 : associe un NSG au subnet et lis les default rules ; compare avec un NSG sur NIC.','Les règles effectives combinent celles du subnet et de la NIC.'],
['Effective security rules','La vue effective sur une NIC aide à expliquer une autorisation ou un refus réel, y compris les règles appliquées par plusieurs NSG.','Sur une NIC existante : Network Watcher → Effective security rules ; cherche la règle gagnante.','Un NSG sans NIC ne prouve pas le trafic final d’une VM.'],
['Azure Bastion','Bastion fournit RDP/SSH vers une VM privée sans exposer une IP publique sur celle-ci ; pense subnet dédié, SKU et réseau peered pris en charge.','Dans le Portal, examine la configuration requise de Bastion avant de le créer, car le service est facturable.','Bastion n’est ni un Load Balancer ni un VPN pour tous les usages.'],
['Service endpoints and private endpoints','Service endpoint sécurise le chemin vers le point public et identifie le subnet ; Private Endpoint place une IP privée pour une instance du service et requiert DNS adapté.','Sur un schéma, dessine client → nom DNS → IP obtenue pour chaque option ; vérifie l’accès réseau et les permissions de données séparément.','Créer un private endpoint sans DNS approprié ne garantit pas que le client l’utilise.']]},
{title:'Name resolution and load balancing',intro:'DNS choisit l’adresse ; l’équilibreur distribue le trafic ; aucun des deux ne remplace les règles de sécurité.',items:[
['Azure DNS','Une DNS zone publique publie des noms Internet ; une private DNS zone liée aux VNets résout des noms privés. Étudie enregistrements A/CNAME et TTL.','Portal → DNS zones / Private DNS zones : crée un schéma nom → zone → IP et explique le VNet link.','La création d’une zone privée sans lien VNet ne donne pas la résolution attendue aux VM.'],
['Azure Load Balancer','Public/internal frontend, backend pool, health probe et load-balancing rule. Load Balancer distribue des flux réseau, pas des règles par URL HTTP.','Dessine frontend → probe → pool → VM ; identifie le port frontend et le port backend.','Une VM unhealthy sort du pool pour la règle concernée.'],
['Troubleshoot load balancing','Vérifie probe health, backend membership, NSG et ports avant de modifier le frontend.','Sur une architecture existante, lis l’état de health probe et les métriques du Load Balancer.','Une règle correcte ne compense pas un service non à l’écoute sur les backends.']]}],sources:[['Networking learning path','https://learn.microsoft.com/en-us/training/paths/az-104-manage-virtual-networks/'],['Network Watcher','https://learn.microsoft.com/en-us/azure/network-watcher/network-watcher-overview'],['Private Endpoint','https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview']]},
monitor:{path:'https://learn.microsoft.com/en-us/training/paths/az-104-monitor-backup-resources/',sections:[
{title:'Azure Monitor and troubleshooting',intro:'Une métrique montre une tendance, un log décrit un événement, une alerte relie la condition à l’action.',items:[
['Metrics and Insights','Metrics sont des séries numériques. Azure Monitor Insights présente des vues adaptées aux VM, Storage et réseaux.','Lab 5 : observe Transactions d’un Storage account et change la plage de temps ; compare Activity Log.','Activity Log est un journal de gestion, pas une courbe de CPU.'],
['Diagnostic settings and logs','Diagnostic settings peut envoyer certaines données vers Log Analytics, Storage ou Event Hubs. Un workspace vide ne collecte pas tout automatiquement.','Portal → une ressource de test → Diagnostic settings : identifie catégories et destinations sans créer de workspace payant si inutile.','La destination choisie et les catégories activées déterminent ce qui devient interrogeable.'],
['KQL queries','Log Analytics utilise KQL pour filtrer, projeter et agréger les enregistrements ; commence par une table, un filtre TimeGenerated et un summarize.','Sur un workspace existant : exécute une requête d’exemple et modifie la période ; sans workspace, lis les exemples de la documentation.','Une requête valide sur une table vide ne prouve pas que la collecte fonctionne.'],
['Alert rules and action groups','Alert rule = scope + signal + condition ; action group = notifications/actions ; alert processing rules modifient le traitement.','Portal → Monitor → Alerts : compose une règle sur métrique sans sauvegarder ; distingue condition et action group.','Une action group seule ne détecte rien.'],
['Network Watcher and Connection Monitor','Network Watcher aide à diagnostiquer IP flow, route, NSG et connectivité ; Connection Monitor suit les tests entre endpoints.','Sur des ressources existantes, compare un diagnostic ponctuel et une surveillance continue.','Un échec peut venir de la destination ou du DNS, pas seulement du NSG.']]},
{title:'Backup and recovery',intro:'Backup récupère un point historique ; Site Recovery réplique et orchestre le basculement.',items:[
['Recovery Services vault and Backup vault','Choisir le coffre compatible avec la charge protégée et le service utilisé. Examine région, redondance et protections du coffre.','Portal → Backup center : parcours les charges prises en charge et le type de vault demandé avant création.','Les deux types de coffre ne sont pas interchangeables pour toutes les charges.'],
['Backup policies and restore','Une policy définit fréquence/rétention ; les points de récupération permettent de restaurer. Il faut vérifier la restauration et la cohérence demandée.','Sur un vault de test, lis une policy et un recovery point ; identifie le RPO implicite selon la fréquence.','Une réplication n’est pas une politique de conservation historique.'],
['Azure Site Recovery and failover','Site Recovery réplique certaines charges et orchestre failover, test failover et failback selon le scénario ; RPO et RTO guident le choix.','Lis un recovery plan d’exemple et dessine site primaire → région secondaire → failover ; n’active pas de réplication payante pour une simple lecture.','Failover non testé ≠ preuve que l’application redémarrera correctement.'],
['Backup reports and alerts','Surveiller résultats de jobs, alertes de sauvegarde et rapports pour repérer des protections défaillantes.','Backup center → Jobs, Alerts et Reports : distingue échec de job et absence de sauvegarde configurée.','Un job réussi ne prouve pas que toutes les ressources attendues sont protégées.']]}],sources:[['Monitor learning path','https://learn.microsoft.com/en-us/training/paths/az-104-monitor-backup-resources/'],['Azure Monitor','https://learn.microsoft.com/en-us/azure/azure-monitor/fundamentals/overview'],['Backup overview','https://learn.microsoft.com/en-us/azure/backup/backup-overview']]}
};
